###
POST http://localhost:8080/api/
Content-Type: application/json

{
  "name" : "aridwiprayogo",
  "password" : "inipasswordrahasia",
  "description" : "alhamdulillah akhirnya selesai juga"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username" : "aridwiprayogo",
  "password" : "inipasswordrahasia"
}

###
GET http://localhost:8080/api/

###
PUT http://localhost:8080/api/{id}

###
DELETE http://localhost:8080/api/{id}