spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    name: postgres
    username: postgres
    password: root
    pool:
      enabled: true
  datasource:
    schema: r2dbc
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    default-schema: 'r2dbc'
    create-schemas: true
    schemas:
      - r2dbc